### ISSUE TITLE
Thanks for your effort and request more details

### ISSUE THREAD

**Issue by ZhehooMorgen** [KernelErr/MoeOS#1]
Hi,
This is Zhenyan from Suzhou, China.

## The MoeOS is awesome!
As a newcomer to embedded development, I spend a few hours trying to get my hands on my new Mango MQ-R.
And I end up running MoeOS on the board. With the blue LED on, the code must be running.
![25P3WGULQ44J}POKQ}6(J_F](https://user-images.githubusercontent.com/22492020/169644253-5d2330d3-7e2b-4be9-9366-fd20dfd988e4.jpg)
This project really helped me a lot!

## A few questions
1. How can I see this output
![VJ`DIBCM8D3_ZZ6{HIT_R7S](https://user-images.githubusercontent.com/22492020/169644296-a5b5b075-684a-4e1d-92fa-10d5bfb502b1.png)
I don't understand what should I do to see this output. It seems that I need to connect it to my computer using a UART adapter. My board has a slightly different pin layout than yours so I don't understand how to connect the wires. And I still have no idea about what bit rate should I use and so on.
2. How to debug the code
Is there any way to debug the code on the board? How to set a breakpoint on the code?
3. How to put the binary on to SD card so that it can run without xfel's help
4. Could you please provide even more details about the steps to run the project?

Thanks again for your awesome project!

Thanks
Zhenyan

**Comment by KernelErr** [comment]
It's so exited for me to hear from you! I am also a beginner in embedded programming and RISC-V. MoeOS actually lacks many things from being a real OS like user space. I created this project just for learning and personal interests. Please give me some time to answer your questions, I am currently not at home.

**Comment by KernelErr** [comment]
1. I am using `sudo minicom -c on` and connecting the board and computer with a CH340 USB to TTL board. Bps is 115200.
2. Actually I don't have an excellent way to debug my program. I basically read the chip document and use UART output to check if it works.
3. This is what I want to do but do not have time to try. There is some example code you could find in Google, they are writing the image file to a specific offset on an SD card. And the SPL program would load the content.
4. The blue LED means the program runs without error. The hardware control is mapped to a specific memory address that you can find in the chip document. Just write to the address so you can control the LED and other things.

**Comment by KernelErr** [comment]
😂 By the way, are you working at Microsoft? This summer I will intern at Microsoft Suzhou.

**Comment by ZhehooMorgen** [comment]
Thanks for your update. That's right, and welcome to Microsoft Suzhou!
I already tried 115200, but it does not work. Probably some issues with the USB to TTL adapter (I not using CH340).
The adapter is from a company called **"Spieed"** and claims that it can be used to debug the D1s chip, but I haven't figured out how to use it.

**Comment by KernelErr** [comment]
You may need to reference the circuit schematic, there might be UART0 RX and TX. Connect debugger' RX to board's TX, vice versa.

**Comment by KernelErr** [comment]
My board is first version of MongoPi MQ. Seems yours is newer version.

**Comment by ZhehooMorgen** [comment]
![IMG_4269](https://user-images.githubusercontent.com/22492020/169654572-ea912ff9-34fa-4f84-a07d-db19a3aa9dae.JPG)
You are right, now I think the debugger might need some special software to work. But the seller did not provide any doc
